# Generated by Django 4.1 on 2024-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCHManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='StaffEmail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
