# Generated by Django 4.1 on 2024-08-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCHManage', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcrs',
            name='Created_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcrs',
            name='Updated_Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Created_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Updated_Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Created_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Updated_Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientcrs',
            unique_together={('ClientIdSubId', 'StaffId', 'FirmClientStaffAssignmentName')},
        ),
    ]
